**3. Hypothesis Testing**

In [8]:
import scipy.stats as stats

**A. Chi-Squared test** 

**This test is used in the case of 2 Categorical values in the dataset**

In [9]:
import seaborn as sns
import pandas as pd
import numpy as np

df = sns.load_dataset('tips')

In [10]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [18]:
dataset_table = pd.crosstab(df['sex'],df['smoker'])
print(dataset_table)

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [20]:
dataset_table.values 

array([[60, 97],
       [33, 54]], dtype=int64)

In [21]:
#Observed Values
Observed_Values = dataset_table.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[60 97]
 [33 54]]


In [22]:
val = stats.chi2_contingency(dataset_table)

In [23]:
val

(0.0,
 1.0,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [24]:
Expected_Values=val[3]

In [25]:
Expected_Values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [26]:
no_of_rows = len(dataset_table.iloc[0:2,0])
no_of_columns = len(dataset_table.iloc[0,0:2])

ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


In [27]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [28]:
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 0.001934818536627623


In [29]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)

Significance level:  0.05
Degree of Freedom:  1
p-value: 0.964915107315732


In [30]:
if p_value <= alpha:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Retain H0,There is no relationship between 2 categorical variables


**T-Test**

**This test is used in the case of Continious values**

**T-test has 2 types : 1. one sampled t-test 2. two-sampled t-test**

In [32]:
df2 = pd.read_csv('t_test.csv')

In [33]:
df2.head()

X
0  131
1  115
2  118
3  120
4  126

In [35]:
len(df.X)

15

In [37]:
mean_X

123.0

In [38]:
from scipy.stats import ttest_1samp

In [45]:
ttest,p_value=ttest_1samp(df.X,120)

In [50]:
print("P Value :",p_value)

P Value : 0.13521173980940243


In [47]:
print("T value : ",ttest) 

T value :  1.585338409406782


In [43]:
if p_value < 0.05:    # alpha value is 0.05 or 5%
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

 we are rejecting null hypothesis
